version: "3"
services:
    api:
      build:
        context: ./
        dockerfile: ./Dockerfile
      ports:
        - "5000:80"
      links:
        - elasticsearch:elasticsearch
      environment:
        - ASPNETCORE_ENVIRONMENT=Docker
    elasticsearch:
      image: elasticsearch
      ports:
        - "9200:9200"
    kibana:
      image: kibana
      ports:
        - "5601:5601"
      links:
        - elasticsearch:elasticsearch